### PR TITLE
Add new DB field last_solrize_end

### PR DESCRIPTION
**Pull request by ghost**
* pvt-get-publishers-documents
* pvt-get-single-document
    
https://github.com/IATI/refresher/pull/278
https://iaticonnect.org/group/9/topic/proposed-update-iati-datastore
https://github.com/IATI/validator-services/pull/402

### CODE REVIEW

**Review by akmiller01 — APPROVED** [review]
Looks good, just make sure to deploy this after refresher migration is applied.

**Review by akmiller01 — CHANGES_REQUESTED** [review]
@odscjames after reviewing validator-web, it may also make sense to add `last_solrize_end` to all endpoints that can return document metadata:

https://github.com/IATI/validator-services/blob/main/database/db.js#L186

and

https://github.com/IATI/validator-services/blob/main/database/db.js#L274

That way, just in case any document that's passed to the `getDocumentDatastoreAvailability` function will not fail to fetch that column.

**Comment by odscjames** [comment]
The first one was already done?

Added second one - thanks

**Comment by akmiller01** [comment]
@odscjames I must have tagged the wrong line, I meant here in the function `getSingleDocumentForName`: https://github.com/IATI/validator-services/blob/2023-08-30/database/db.js#L319

**Comment by odscjames** [comment]
Made change

**Review by akmiller01 — APPROVED** [review]
Looks good!

**Pull request merged**
